apiVersion: v1
kind: Pod
metadata:
  name: tuongvx
  labels:
    app: redmineapp
  #annotations:
    #snapshotPolicy: "checkpoint"
    #snapshotPath: "/var/lib/kubelet/migration/abc"
spec:
  containers:
  - name: tuong
    image: tuongvx/redmine
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
      protocol: TCP
    volumeMounts:
      # name must match the volume name below
    - name: nfs-log
      mountPath: /usr/src/redmine/log
    - name: nfs-files
      mountPath: /usr/src/redmine/files
    # - name: nfs-publib
    #   mountPath: /usr/src/redmine/publib
    # - name: nfs-plugins
    #   mountPath: /usr/src/redmine/plugins
    # - name: nfs-public
    #   mountPath: /usr/src/redmine/public
    - name: nfs-sqlite
      mountPath: /usr/src/redmine/sqlite
  volumes:
  - name: nfs-log
    hostPath:
      path: /var/lib/kubelet/migration/redmine/log
      type: Directory
  - name: nfs-files
    hostPath:
      path: /var/lib/kubelet/migration/redmine/files
      type: Directory
  # - name: nfs-publib
  #   hostPath:
  #     path: /var/lib/kubelet/migration/redmine/publib
  #     type: Directory
  # - name: nfs-plugins
  #   hostPath:
  #     path: /var/lib/kubelet/migration/redmine/plugins
  #     type: Directory
  # - name: nfs-public
  #   hostPath:
  #     path: /var/lib/kubelet/migration/redmine/public
  #     type: Directory
  - name: nfs-sqlite
    hostPath:
      path: /var/lib/kubelet/migration/redmine/sqlite
  nodeSelector:
    kubernetes.io/hostname: worker1
